grammars/graphql.json, package-lock.json, package.json
- in multiline comments
Closes https://github.com/prismagraphql/vscode-graphql/issues/19 and https://github.com/prismagraphql/vscode-graphql/issues/30
=> Fix syntax highlighting

package.json
Fixes https://github.com/prismagraphql/vscode-graphql/issues/41
=> Remove language packs

package-lock.json, package.json
Fixes https://github.com/prismagraphql/vscode-graphql/issues/49
We can make this client configurable in future.
=> fix: add support for graphql tag in TS

src/client/graphql-codelens-provider.ts, src/client/source-helper.ts, src/extension.ts
This adds support for executing queries via the CodeLens
from .graphql files. It also adds support for .graphql files
with multiple queries.
=> Add support for executing queries from graphql files

.circleci/config.yml
for issue #45. This is a draft PR. I have set up the basic pipeline which will run test, package command and store artifact into `/tmp` folder. Next, we need to setup vsce workflow to publish the extension to the marketplace referring https://code.visualstudio.com/docs/extensions/publish-extension doc.
=> WIP: CI/CD setup using CircleCI

.circleci/config.yml
=> Update config.yml using master branch

src/CustomInitializationFailedHandler.ts, src/extension.ts
Fixes https://github.com/prisma/vscode-graphql/issues/7
=> fix(error): handle missing graphql-config

package-lock.json, package.json, src/CustomInitializationFailedHandler.ts
Fixes https://github.com/prisma/vscode-graphql/issues/89
=> fix(cpu): infinite initialization loop on error other than non-exisent file

package.json
=> Remove theme category

.envrc_sample, .github/workflows/publish.yml, .gitignore, README.md, package-lock.json, package.json, publish.sh
via PAT https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token
=> feat(automate release)

.vscode/settings.json, grammars/graphql.json, package.json, src/extension.ts
=> fix(grammar) end in graphql-variable-assignment

grammars/graphql.json
improve grammar support in graphql - we need directive definitions and improved comment support for arguments (input arguments, directives, etc)
borrowed from https://github.com/zth/vscode-reasonml-graphql, thanks @zth
=> feat: grammar - directive definitions, comments

renovate.json
=> CI: add no-automerge on minor as well

src/client/source-helper.ts
- Removes scalar validation as it is impossible to know what data type it should validate.
- Fixes JSON objects passing Int / Float / Boolean validation
@acao
=> fix: Improve input validation on query execution

README.md, package.json, src/client/graphql-codelens-provider.ts, src/extension.ts
matching PR for graphql/graphiql#1665
also rename generic commands so they don't clash
TODO: wait for package bump
=> improvement: allow new useSchemaFileDefinition LSP setting

package.json, src/status/index.ts
Fixes #224. Replaced the last remains of `extension` references with `vscode-graphql`.
=> fix(#224): Updated 'extension' -> 'vscode-graphql'

README.md
Some updates and improvements to the instructions. This is a trivial PR, so I'll merge it directly.
Signed-off-by: Brian Warner <brian@bdwarner.com>
=> Update EasyCLA info

grammars/graphql.re.json, grammars/graphql.rescript.json, package.json
It would be great to have this supported! Let me know if what you think of this commit?
=> feature: embedded rescript & reason highlighting support

package.json
Attempt to fix #292 but unfortunately untested due to my lack of vscode extension dev experience.
=> Add source.svelte to injectTo file targets

README.md, package.json, src/client/network-helper.ts
Fixes https://github.com/graphql/vscode-graphql/issues/241
=> Add setting to bypass certificate verification

.vscode/extensions.json, README.md, package-lock.json, package.json
This LSP server update should fix all issues with `schema` config for both SDL files and urls.
Upgrades with these patches which will vastly improve the stability of the server
https://github.com/graphql/graphiql/pull/2055
=> fix: upgrade language server, fix major issues

src/client/network-helper.ts
=> Adds condition to only create a ws client when executing a subscription operation

package-lock.json, package.json, src/extension.ts
This upgrade for the LSP server should fix windows and special character path issues, variables completion issues, and also radically improve completion options in more contexts by introducing more triggerCharacters in the LSP server
=> upgrade lang server, more extensions

src/client/network-helper.ts
Fixes #321
This is caused by using the https agent here, we could also opt to use the regular http-agent
=> (fix) - check protocol for https and else disable agent

package-lock.json, package.json, src/client/graphql-content-provider.ts
=> fix: escape response html

package-lock.json, package.json
Some nice improvements in the GLS to provide today :)
- auto-expansion & completion for leaf sets
- better argument insert text/completion
- more completion characters! like a lot. newlines, many new places for completion
remember to use `documents` for files with `fragments`!
and all of your schema SDL files should be present in `schema` config, with globs, single files, etc
=> chore: upgrade the language server

src/extension.ts
Provides more visibility into what's going on when running the restart command
=> Adds logs to the restart command

README.md
current link in README is broken
=> docs: update link to graphql-config usage

.changeset/loud-balloons-add.md, package-lock.json, package.json
One more patch for windows users
=> upgrade LSP server!
