- README.md
Add instructions for logging `graphql-language-service` / `ts-language-service`. Fixes https://github.com/prismagraphql/vscode-graphql/issues/28
> Document development setup for logging language service(s)

- src/extension.ts
Fixes https://github.com/prismagraphql/vscode-graphql/issues/26
Move popup to a output channel log.
> fix: extension click, replace popup with log

- README.md
Currently the README marks that the project NEEDS a `.graphqlconfig.yml` file when in fact it also supports a `.graphqlconfig`. Confirmed it locally to also support it.
> Add that extension also accepts a .graphqlconfig file

- README.md
Without it, the GraphQL language server complains that it is missing.
> Add watchman to installation instructions

- package-lock.json
- package.json
- src/extension.ts
This mostly fixes https://github.com/prisma/vscode-graphql/issues/60 by launching the GraphQL Language Server with variables from `.env` added to its environment.
The bigger issue however is that there is no visible error when the language server fails to parse the config file (e.g. when an environment variable doesn't exist at all, or for any other reason).
> Launch language server with environment from .env file (fixes #60)

- src/extension.ts
- src/server/server.ts
This enables the graphql language server extension when in javascript files which will enable autocomplete when using tagged templates. This combined with https://github.com/graphql/graphiql/pull/883 will fix autocomplete with the gql tagged template.
Fixes #61 
Fixes #21 
Fixes #53 
Fixes #96
> Add support for autocomplete from javascript files

- README.md
The linked GraphQL config repository points at the latest version 3 of the spec, but this plugin implements a previous version. This makes that version clear.
> docs: Update README to point to graphql-config v2

- package.json
- src/extension.ts
As a small workaround for [Does not work when updating the schema](https://github.com/prisma-labs/vscode-graphql/issues/104) and from this [suggestion](https://github.com/prisma-labs/vscode-graphql/issues/104#issuecomment-642311198):
This PR proposes a command to restart the gql plugin.  So, instead of restarting vs-code, a user can do ctrl-shift-p to pull up the Command Palette and type something like "graphql restart".
It's not great, but as the cantiero indicates, "Beats restarting the editor for sure".
> feat: add restart option to vscode-graphql command pallate

- grammars/graphql.json
in #183 we forgot this!
Before, we had just fixed inline argument comments for directive definitions and other types with inline arguments, but we had not solved the top-level keyword/etc definition issue. graphql 15 Directive definitions before #183 were still almost all green, unhighlighted!
Before (after #183):
After:
> fix: be sure to register directive def at source scope in grammar

- .github/workflows/test.yml
- package-lock.json
- package.json
Since commit https://github.com/prisma-labs/vscode-graphql/commit/bb93c44cc856318ce8c113940872bfe7deef1132#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 the CI has been failing silently because of peer dependency issues. Therefore downgrading to `0.12.x` for dep `graphql` .
cc @acao
> fix: Downgrade graphql config

- package.json
- src/extension.ts
> improvement: associate with graphqls file extension

- README.md
we still need to set up tooling to keep the insiders edition up to date, so for now, we will remove it from the readme
> chore: remove insiders statement for now

- CHANGELOG.md
- package-lock.json
- package.json
just manually track the changelog for now, with a general summary
Solves #219 
also solves #218 where `.gql` extension was not working
> chore: bump gls server for improvements, add changelog

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- src/extension.ts
- updates for transfer from Prisma > GraphQL
- require `dotenv` in the server runtime (for loading graphql config values), and allow a `graphql-config.dotEnvPath` configuration to specify specific paths
- reload server on workspace configuration changes
- reload severside `graphql-config` and language service on config file changes. definitions cache/etc will be rebuilt
- note: client not configured to reload on graphql config changes yet (i.e endpoints)
- accept all `graphql-config.loadConfig()` options
> improvement: server dotenv and config reloading

- README.md
- grammars/graphql.markdown.codeblock.json
- package.json
Closes https://github.com/graphql/vscode-graphql/issues/78
Contributes to https://github.com/graphql/vscode-graphql/issues/138
This adds support for highlighting of markdown fenced code blocks, e.g.:
```md
```gql
```graphql
```
> feat: support highlighting markdown fenced code blocks

- README.md
It's a small thing in the readme, but a big issue for inexperienced users like me 😅 (took me 15 min to realize this 🙈 )
> docs: fix typo in simple example

- src/client/graphql-codelens-provider.ts
- src/client/source-helper.ts
'Execute Query' below ``gql` `` is shown one line down.
Expected behavior:
Actual:
> fix: 'Execute Query' below gql` is shown one line down

- package-lock.json
- package.json
- src/client/network-helper.ts
After #338 the extension fails to load on workspaces without react installed.
react is imported by the bundled urql package.
Using the @urql/core package instead solves the issue.
Closes #345
> fix: use @urql/core instead of urql to not pull react

- .github/workflows/test.yml
this should prevent some issues we usually only see on publish
> vsce package in ci to check deps

- .vscodeignore
- CHANGELOG.md
this will make the bundle size much smaller I'll bet. Currently the extension weighs in at 7.8mb. lets see what this does for us!
> smaller bundle

- README.md
JS comment breaks yaml files. Fixed comment and code block highlighting type to match contents.
> Use yaml formatting for yaml example

- README.md
- src/extension.ts
- src/status/index.ts
This enables the extension in vue files as well. 
Doesn't quite work yet and depends on a proper implementation of the server backend: https://github.com/graphql/graphiql/issues/1678
> Enable in vue files

- README.md
- src/extension.ts
- src/status/index.ts
Reverts graphql/vscode-graphql#307
This PR did _not_ introduce a grammar configuration for syntax highlighting in vue files, causing a parsing error
> Revert "Enable in vue files"

- grammars/graphql.json
GraphQL directives can be added to many places:
https://spec.graphql.org/draft/#sec-Type-System.Directives
Currently not all places listed in the spec are supported for syntax highlighting. Especially many type system directive locations are missing. This pull request adds the missing places to the grammar, so that directives are syntax highlighted on all possible places.
Potentially this also fixes issue #289.
> Add directive highlighting for type system directives

- .changeset/silver-radios-invent.md
- package.json
- src/client/graphql-codelens-provider.ts
It partially fixes #232.
(Completions still don't work; we may need to fix graphql-language-service-server.)
> feat: provide 'Execute Query' for /* GraphQL */ templates

- README.md
For IntelliJ users and otherwise
We can't enable this by default in the language server because some of the features were intentionally deprecated because of their resource intensiveness. For example, nested config files. `graphqlConfig.loadSchema()` is invoked on most editor operations, so the config is re-fetched frequently.
> add `legacy` graphql config information

- .changeset/two-numbers-occur.md
- src/status/index.ts
Avoids:
Only sets the color when it is an error, and it uses the theme API to grab a warning colour. Unsure if this will be perfect, but bright red wasn't going to work in all cases either 👍🏻
> Use the theme API to set the right colours for the status bar item

- .changeset/silly-days-march.md
- package.json
- src/extension.ts
- src/status/index.ts
As knowing whether you are in debug or not isn't too useful from a users perspective
> Show the output channel when clicking on graphql status bar

- .changeset/quick-rabbits-hunt.md
- package.json
Replace `*` for activation when `package.json` is present, the only exception for `graphql-config`
> Activation event for package.json files
